Vagrant.configure("2") do |config|
  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "bento/ubuntu-16.04" 
    webserver.vm.network "private_network", ip: "192.168.1.2"
    webserver.vm.hostname = "webserver"

  end
  config.vm.define "webserver" do |webserver|
    ansible.vm.box = "bento/ubuntu-16.04" 
    ansible.vm.network "private_network", ip: "192.168.1.2254"
    ansible.vm.hostname = "ansible"

  end
 end
